
#ifndef siren
#define siren

#define BUFSIZE 				2048
#define SERVICE_PORT    			21234

//RTL_SDR OPTIONS
#define BUFFER_SIZE				512			//POPEN BUFFER SIZE 					DEFAULT: 512
#define FREQUENCY				"147480000"	//LISTEN FREQUENCY IN HZ 				DEFAULT: 147.48MHZ		***NOTE*** CHANGING THIS MAY BREAK FCC REGULATIONS ***ONLY USE WITH HAM RADIO LICENSE ***NOTE***
#define PPM_ERROR				"0"     	//PARTS PER MILLION SDR CORRECTION 			DEFAULT: 0
#define SAMPLE_RATE 				"22000"		//RTL_FM SAMPLE RATE IN HZ				DEFAULT: 22KHZ 			***NOTE*** CHANGING THIS MAY BREAK MULTIMON-NG ***NOTE***


//SIREN OPS OPTIONS
#define CODE_LENGHT				5			//SIREN ACTIVATION CODE LENGHT
#define CODE_CHAR_TIMEOUT 			5			//SIREN CHAR TIMEOUT. NUMBER OF SECONDS SINCE LAST CHAR TO RESET DTMF STRING
#define CODE_SIREN_OFF				"42061"		//SIREN OFF    CODE 	***NOTE*** MUST BE EXCATLY THE LENGHT OF CODE_LENGHT ***NOTE***
#define CODE_SIREN_GROWL			"42062"    	//SIREN GROWL  CODE	***NOTE*** MUST BE EXCATLY THE LENGHT OF CODE_LENGHT ***NOTE***
#define CODE_SIREN_ALERT 			"42063"    	//SIREN ALERT  CODE 	***NOTE*** MUST BE EXCATLY THE LENGHT OF CODE_LENGHT ***NOTE***
#define CODE_SIREN_ATTACK 			"42064"		//SIREN ATTACK CODE 	***NOTE*** MUST BE EXCATLY THE LENGHT OF CODE_LENGHT ***NOTE***

//SIREN PWM OPTIONS
#define SIREN_PWM_CUTOFF		550			//SIREN PWM VOLTAGE CUTOFF
#define SIREN_PWM_GROWL 		595			//SIREN PWM VOLTAGE FOR GROWL FUNCTION
#define SIREN_PWM_ALERT			1024		//SIREN PWM VOLTAGE FOR ALERT FUNCTION
#define SIREN_PWM_ATTACK_MAX		1024		//SIREN PWM VOLTAGE FOR ATTACK MAX VOLTAGE
#define SIREN_PWM_ATTACK_MIN		750			//SIREN PWM VOLTAGE FOR ATTACK MIN VOLTAGE

//SIREN TIMING OPTIONS
#define SIREN_TIME_GROWL_REVUP		0.10		//SIREN TIMING FOR REVUP ON GROWL FUNCTION
#define SIREN_TIME_ALERT_REVUP		3.417		//SIREN TIMING FOR REVUP ON ALERT FUNCTION
#define SIREN_TIME_ATTACK_REVUP		10.8		//SIREN TIMING FOR REVUP ON ATTACK FUNCTION
#define SIREN_TIME_ATTACK_REVDOWN	15.4		//SIREN TIMING FOR REVDOWN ON ATTACK FUNCTION
#define SIREN_TIME_ATTACK_HOLD		3000		//SIREN TIMING FOR REVUP ON GROWL FUNCTION

//RASPBERRYPI OPTIONS
#define PWM_PIN 			1		//PWM PIN ON PI 				***NOTE*** ON REV 1 BOARDS USE 1 AS THIS IS BCM PIN 18 ***NOTE***
#define ACTLED_PIN 			3		//RED LED INDICATING SIREN IS ON 			
#define DTMFLED_PIN 			0		//BLUE LED THAT FLASHES ON DTMF CHAR RECIVED
#define ONLED_PIN 			2		//GREEN LED THAT INDICATES CODE IS RUNNING

char dtmf_string[CODE_LENGHT + 1];				//DTMF CHARS CAPTURED
int dtmf_count;

//siren.c
void  SirenStop  (int cur);				//THIS FUNCTION REVS DOWN THE SIREN AND KILLS THE PWM HOLD ON THE PIN
void* SirenGrowl (void *c);				//THIS FUNCTION REVES THE SIREN UP TO A GROWL UNTIL CNCL = 1 THE IT CALLS SIRENSTOP()
void* SirenAlert (void *c);				//THIS FUNCTION REVES THE SIREN UP TO ALERT UNTIL CNCL = 1 THE IT CALLS SIRENSTOP()
void* SirenAttack(void *c);				//THIS FUNCTION REVES THE SIREN UP TO ATTACK AND WAILS UNTIL CNCL = 1 THE IT CALLS SIRENSTOP()
void  SoundSiren (int mode, int *go);			//THIS FUNCTION CREATES A THREAD FOR THE SIREN FUNCTION THEN PASSES CNCL VAR

//netcli.c
void  ACTcheck (char *dtmf, int *Cancel_Var);  		//THIS FUNCTION CHECKS THE DTMF CHAR

//Radio.c
void CleanChar (char *var);
void DTMFcheck (char *dtmf, int *Cancel_Var);
void DTMFhandel (char *dtmf, int charcount, int timestamp,int *Cancel_Var);

//airraid.c
void helper();

#endif
